# Generated by Django 5.1.6 on 2025-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/category/', verbose_name='Maxsulot kategoriyasi rasmi')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Maxsulot kategoryasi nomi')),
            ],
            options={
                'verbose_name_plural': 'Maxsulot kategoriyasi',
            },
        ),
    ]
