# Generated by Django 5.1.6 on 2025-02-07 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Maxsulot kategoriyasi'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='samagro.productcategory', verbose_name='Ota Kategoriya'),
        ),
    ]
