# Generated by Django 5.1.6 on 2025-02-07 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0002_alter_productcategory_options_productcategory_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/img/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Maxsulot nomi')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Maxsulot narxi')),
                ('text', models.TextField(blank=True, null=True, verbose_name="Maxsulot haqida ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='O‘zgartirilgan vaqt')),
                ('images', models.ManyToManyField(blank=True, to='samagro.productpicture', verbose_name='Maxsulot rasmlari')),
                ('productcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samagro.productcategory', verbose_name='Maxsulot turi')),
            ],
        ),
    ]
