# Generated by Django 5.1.6 on 2025-02-09 08:42

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0002_users_groups_users_is_staff_users_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Sarlovha rasmi')),
                ('title', models.CharField(help_text='Sarlavha maksimal 200 belgi', max_length=200, null=True, verbose_name='Sarlovhasi')),
                ('text', models.CharField(help_text='Sarlavha matini maksimal 500 belgi', max_length=500, null=True, verbose_name='Sarlovha matini')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Sarlovha umumiy matini')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
            options={
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
