# Generated by Django 5.1.6 on 2025-02-09 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0003_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
