# Generated by Django 5.1.6 on 2025-02-07 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0003_productpicture_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpicture',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': 'Rasmlar'},
        ),
    ]
