# Generated by Django 5.1.6 on 2025-02-07 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0004_alter_productpicture_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Maxsulot', 'verbose_name_plural': 'Maxsulotlar'},
        ),
    ]
