# Generated by Django 5.1.6 on 2025-02-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Ko'cha nomi"),
        ),
    ]
