# Generated by Django 5.1.6 on 2025-02-07 17:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0005_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name="Maxsulot haqida umumiy ma'lumot"),
        ),
    ]
