# Generated by Django 5.1.6 on 2025-02-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0006_products_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date_end_discount',
            field=models.DateField(blank=True, null=True, verbose_name='Chegrima tugash vaqti'),
        ),
        migrations.AddField(
            model_name='products',
            name='is_discount',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Chegirma berish'),
        ),
        migrations.AddField(
            model_name='products',
            name='price_discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Maxsulot chegirma narxi'),
        ),
    ]
