# Generated by Django 5.1.6 on 2025-02-08 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0007_products_date_end_discount_products_is_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='percent_discount',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Chegirma foizi'),
        ),
    ]
