# Generated by Django 5.1.6 on 2025-02-11 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0008_alter_comments_comment_alter_comments_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Yaratilgan vaqt'),
        ),
    ]
