# Generated by Django 5.1.6 on 2025-02-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0008_products_percent_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maxsulot narxi'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price_discount',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maxsulot chegirma narxi'),
        ),
    ]
