# Generated by Django 5.1.6 on 2025-02-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0009_alter_products_price_alter_products_price_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frist_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foydalanuvchi ismi:')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Foydalanuvchi familiyasi:')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name="Ko'cha manzili")),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ko'chas nomi")),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Telefon nomer')),
            ],
        ),
    ]
