# Generated by Django 5.1.6 on 2025-02-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0009_alter_comments_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Fayl'),
        ),
    ]
