# Generated by Django 5.1.6 on 2025-02-09 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0010_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='content',
        ),
    ]
