# Generated by Django 5.1.6 on 2025-02-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samagro', '0010_comments_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='files',
        ),
        migrations.AddField(
            model_name='news',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='file/', verbose_name='Fayl'),
        ),
    ]
